// 화면 카피 상수 - 토스트/검증 메시지와 분리해 변하기 쉬운 안내 문구를 관리
export const UI_COPY = {
  common: {
    loading: '불러오는 중...',
    retry: '새로고침',
    cancel: '취소',
    delete: '삭제',
    deleting: '삭제 중...',
    search: '검색',
    add: '추가',
    adding: '추가 중...',
    upload: '업로드',
  },
  system: {
    authTokenRequired: '인증 토큰이 필요합니다.',
    loginRequired: '로그인이 필요합니다.',
    loginRequiredForFeature: '로그인 후 이용할 수 있는 기능입니다.',
    workspaceIdentifierRequired: '워크스페이스 식별자가 필요합니다.',
  },
  loginRequiredDialog: {
    title: '로그인이 필요해요',
    description: '해당 기능을 이용하시려면 먼저 로그인해주세요.',
    action: '로그인 하기',
  },
  auth: {
    pageTitle: '인증',
    brandTitle: '코스잇다',
    subtitle: '코스 계획을 시작해보세요 ☺️',
    accountCardTitle: '계정',
    accountCardDescription: '로그인하거나 새 계정을 만드세요',
    loginTab: '로그인',
    registerTab: '회원가입',
    loginForm: {
      emailPlaceholder: '이메일',
      passwordPlaceholder: '비밀번호',
      submit: '로그인',
      submitting: '로그인 중...',
    },
    registerForm: {
      nicknamePlaceholder: '닉네임',
      emailPlaceholder: '이메일',
      passwordPlaceholder: '비밀번호',
      confirmPasswordPlaceholder: '비밀번호 확인',
      checkAction: '확인',
      checkingAction: '확인 중...',
      nicknameAvailable: '✓ 사용 가능한 닉네임입니다',
      nicknameDuplicated: '사용중인 닉네임입니다',
      nicknameMinLength: '최소 2자 이상',
      nicknameMaxLength: '최대 20자 이하',
      invalidEmailFormat: '유효하지 않은 이메일 형식입니다',
      emailDuplicated: '이미 사용중인 이메일입니다',
      emailAvailable: '✓ 사용 가능한 이메일입니다',
      passwordMinLength: '최소 6자 이상',
      passwordMaxLength: '최대 20자 이하',
      passwordMismatch: '비밀번호가 일치하지 않습니다.',
      submit: '회원가입',
      submitting: '가입 중...',
    },
  },
  notFound: {
    pageTitle: '페이지 오류',
    title: '페이지를 찾을 수 없습니다',
    description: '요청하신 페이지가 존재하지 않거나 이동되었습니다.',
    action: '홈으로 돌아가기',
  },
  myPage: {
    pageTitle: '마이페이지',
    logout: '로그아웃',
  },
  landing: {
    hero: {
      line1: '시작은 간편하게',
      line2: '마무리는 완벽하게',
      brand: '코스잇다',
      suffix: '에서!',
      description: '처음부터 고민하지 말고, 필요한 카테고리만 골라 간편하게 시작하세요.',
      start: '시작하기',
      moveToWorkspace: '내 워크스페이스로 이동',
      exploreCommunity: '커뮤니티 둘러보기',
    },
    problemsTitle: '이런 고민, 있지 않나요?',
    featuresTitle: '핵심 기능',
    stepsTitle: '이렇게 사용해요',
    problems: [
      {
        title: '분산된 정보',
        description: '지도 즐겨찾기, 메모, 채팅에 흩어진 장소를 한 곳에서 체계적으로 관리하기 어렵습니다.',
      },
      {
        title: '장소 탐색 피로도',
        description: '내 취향에 맞는 코스 정보를 찾기 위해 여러 플랫폼을 오가며 탐색해야 합니다.',
      },
      {
        title: '복잡한 코스 선정 과정',
        description: '장소를 찾은 뒤에도 순서 정리와 동선 확인까지 직접 하려면 시간이 오래 걸립니다.',
      },
    ],
    features: [
      {
        title: '커뮤니티 탐색과 저장',
        description: '다른 사용자가 공유한 카테고리를 둘러보고, 마음에 드는 카테고리를 내 보관함에 모을 수 있습니다.',
      },
      {
        title: '커스텀 코스 제작',
        description: '카테고리 순서를 편집하고 대표 장소를 정해, 완벽한 일정을 만들 수 있습니다.',
      },
      {
        title: '지도 기반 시각화',
        description: '카테고리별 색상 마커와 대표 장소 경로로 동선을 한눈에 확인할 수 있습니다.',
      },
      {
        title: '공유와 재사용',
        description: '내가 만들어둔 카테고리를 재사용하거나 공유할 수 있습니다.',
      },
    ],
    steps: [
      {
        number: '01',
        title: '커뮤니티에서 카테고리를 찾습니다',
        description: '다른 사용자가 공유한 카테고리를 둘러보고, 원하는 카테고리를 고릅니다.',
      },
      {
        number: '02',
        title: '워크스페이스로 가져옵니다',
        description: '고른 카테고리를 내 워크스페이스 일정으로 불러와 바로 사용합니다.',
      },
      {
        number: '03',
        title: '필요한 만큼만 커스텀합니다',
        description: '카테고리 순서를 편집하고 대표 장소를 설정해 일정 흐름을 정리합니다.',
      },
      {
        number: '04',
        title: '완성한 카테고리를 다시 공유합니다',
        description: '내가 다듬은 카테고리를 공유해 다른 사용자도 쉽게 코스를 시작할 수 있습니다.',
      },
    ],
  },
  myWorkspace: {
    pageTitle: '내 워크스페이스',
    createAction: '새 워크스페이스',
    titleRequired: '워크스페이스 제목을 입력해주세요.',
    empty: {
      title: '워크스페이스가 없습니다.',
      description: '지금 추가해보세요!',
    },
    deleteDialog: {
      title: '워크스페이스 삭제',
      description: (title: string) => `"${title}" 워크스페이스를 정말 삭제하시겠습니까?`,
      warning: '이 작업은 되돌릴 수 없으며, 모든 카테고리와 장소 정보가 함께 삭제됩니다.',
    },
  },
  workspaceDialog: {
    create: {
      title: '새 워크스페이스',
      fieldLabel: '제목',
      placeholder: '예: 홍대 데이트 코스',
      cancel: '취소',
      submit: '생성',
      submitting: '생성 중...',
    },
    edit: {
      title: '워크스페이스 이름 바꾸기',
      fieldLabel: '제목',
      placeholder: '예: 홍대 데이트 코스',
      cancel: '취소',
      submit: '확인',
      submitting: '수정 중...',
    },
  },
  myCategory: {
    pageTitle: '내 카테고리',
    createAction: '새 카테고리',
    nameRequired: '카테고리 이름을 입력해주세요.',
    placeSearchKeywordRequired: '검색어를 입력해주세요.',
    placeSearchNoResult: '검색 결과가 없습니다.',
    placeAlreadyAdded: '이미 추가된 장소입니다.',
    atLeastOnePlace: '장소를 1개 이상 추가해주세요.',
    empty: {
      title: '카테고리가 없습니다.',
      description: '지금 추가해보세요!',
    },
    detailDialog: {
      placeListTitle: '장소 목록',
      noPlacesInDetail: '표시할 장소가 없습니다.',
    },
    editorDialog: {
      createTitle: '새 카테고리 추가',
      editTitle: '카테고리 수정',
      nameLabel: '카테고리 이름',
      namePlaceholder: '예: 맛집 투어',
      selectedPlacesLabel: '추가된 장소',
      placeSearchLabel: '장소 검색',
      placeSearchPlaceholder: '장소 이름이나 주소 검색',
      searchAction: '검색',
      searching: '검색 중...',
      noPlacesSelected: '선택한 장소가 없습니다.',
      removePlaceAriaLabel: '장소 제거',
      addPlaceAction: '추가',
      cancel: '취소',
      create: '생성',
      creating: '생성 중...',
      edit: '수정',
      editing: '수정 중...',
    },
    deleteDialog: {
      title: '카테고리 삭제',
      description: (title: string) => `"${title}" 카테고리를 정말 삭제하시겠습니까?`,
      warning: '이 작업은 되돌릴 수 없으며, 카테고리에 포함된 장소 정보도 함께 삭제됩니다.',
    },
  },
  categoryDialog: {
    add: {
      title: '카테고리 추가',
      colorLabel: '색상 선택',
      suggestedLabel: '추천 카테고리',
      manualInputLabel: '직접 입력',
      manualInputPlaceholder: '카테고리 이름',
      cancel: '취소',
      submit: '추가',
      submitting: '추가 중...',
    },
    edit: {
      title: '카테고리 수정',
      colorLabel: '색상 선택',
      nameLabel: '카테고리 이름',
      namePlaceholder: '카테고리 이름',
      cancel: '취소',
      submit: '확인',
      submitting: '수정 중...',
    },
  },
  myPosts: {
    pageTitle: '내 게시물',
    sectionTitle: '업로드한 카테고리',
    uploadAction: '업로드하기',
    empty: {
      title: '업로드한 카테고리가 없습니다.',
      description: '내 카테고리를 업로드해보세요.',
    },
    deleteDialog: {
      title: '게시물을 삭제할까요?',
      description: (title: string) => `"${title}" 게시물을 삭제합니다.`,
      warning: '삭제 후에는 복구할 수 없습니다.',
    },
  },
  workspaceDetail: {
    notFound: '워크스페이스를 찾을 수 없습니다.',
    createAction: '새 워크스페이스',
    mapNotReady: '네이버 지도 설정이 완료되지 않았습니다. 관리자에게 문의해주세요.',
  },
  community: {
    pageTitle: '커뮤니티',
    recommendedTitle: '코스잇다 추천 카테고리',
    boardTitle: '카테고리 게시판',
    boardPageTitle: '카테고리 게시판',
    uploadFabLabel: '업로드',
    searchPlaceholder: '장소 카테고리를 찾아보세요',
    emptySearchResult: '검색 결과가 없습니다.',
  },
  toaster: {
    close: '닫기',
  },
  categoryList: {
    title: '카테고리',
    addAction: '추가',
    importAction: '불러오기',
    createAction: '생성하기',
    loadFailed: '카테고리를 불러오지 못했습니다. 잠시 후 다시 시도해주세요.',
    emptyDescription: '카테고리를 추가해보세요',
  },
  communitySearch: {
    sectionTitle: '추천 검색어',
    regionTitle: '🗺️ 지역',
    foodTitle: '🍽️ 식사',
    activityTitle: '🎯 활동',
  },
  searchResult: {
    pageTitle: '검색 결과',
    sectionTitle: '검색 결과',
  },
  userMenu: {
    sheetTitle: '메뉴',
    storageSection: '보관함',
    communitySection: '커뮤니티',
    accountSection: '계정',
    myWorkspace: '내 워크스페이스',
    myCategory: '내 카테고리',
    communityExplore: '커뮤니티 둘러보기',
    myPosts: '내 공유 목록',
    myPage: '마이페이지',
    login: '로그인',
    logout: '로그아웃',
  },
  navigationDrawer: {
    sheetTitle: '메뉴',
    workspaceSection: '워크스페이스',
    createWorkspace: '새 워크스페이스',
  },
  uploadCategoryDialog: {
    title: '카테고리 업로드',
    empty: {
      title: '업로드 할 카테고리가 없습니다.',
      description: '내 카테고리에서 먼저 만들어보세요.',
      action: '내 카테고리 만들러 가기',
    },
  },
  importCategoryDialog: {
    title: '카테고리 불러오기',
    savedTab: '내 보관함',
    savedEmpty: '내 보관함에 카테고리가 없습니다.',
  },
  placeSearchDialog: {
    title: '장소 검색',
    description: '장소를 검색하고 추가하세요',
    placeholder: '장소 이름이나 주소 검색',
    searchAction: '검색',
    searching: '검색 중...',
    addAction: '추가',
    addingAction: '추가 중...',
    keywordRequired: '검색어를 입력해주세요.',
    noResult: '검색 결과가 없습니다.',
  },
  place: {
    linkMissing: '장소 링크가 없습니다.',
    openSearchAction: '장소 검색',
  },
  map: {
    browserLocationUnsupported: '이 브라우저에서는 위치 정보를 지원하지 않습니다.',
    mapNotReady: '지도가 아직 준비되지 않았습니다.',
    locationPermissionDenied: '위치 권한이 거부되었습니다. 브라우저 설정을 확인해주세요.',
    locationFetchFailed: '현재 위치를 가져오지 못했습니다. 다시 시도해주세요.',
  },
} as const;
